build-DurableClientLayer:
	mkdir -p $(ARTIFACTS_DIR)/nodejs/node_modules/@aws-sdk
	cp -r client-lambda $(ARTIFACTS_DIR)/nodejs/node_modules/@aws-sdk/
	rm -rf $(ARTIFACTS_DIR)/nodejs/node_modules/@aws-sdk/client-lambda/node_modules
